version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433
  security-alert-api:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi --log-file -
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    restart: always

    depends_on:
      - db
volumes: 
  db: