version: "3.9"

services:
  security-alert-api:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    restart: always
