version: "3.9"

services:
  security-alert-api:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi --log-file -"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    restart: always
