version: "3.9"

services:
  db:
    image: postgres
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5431
  security-alert-api:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi --log-file -
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    restart: always
    
    depends_on:
      - db