version: "3.9"

services:
  db:
    image: postgres:12
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434
    restart: always
  security-alert-api:
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    expose:
      - 8000
    restart: always

    depends_on:
      - db
volumes: 
  postgres_data: