# Generated by Django 4.1.3 on 2023-03-10 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts_profile", "0001_initial"),
        ("incident", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("price", models.FloatField(default=0)),
                ("max_no_of_users", models.IntegerField(default=0)),
                (
                    "duration",
                    models.IntegerField(
                        default=1, help_text="Duration of the package in months"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_users", models.IntegerField(default=1)),
                ("amount", models.IntegerField(default=0)),
                ("duration", models.IntegerField(default=1)),
                ("expiry_date", models.DateTimeField(null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("", ""), ("INVOICE", "INVOICE"), ("PAID", "PAID")],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("EXPIRED", "EXPIRED")],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                (
                    "affected_groups",
                    models.ManyToManyField(null=True, to="incident.affectedgroup"),
                ),
                (
                    "alert_type",
                    models.ManyToManyField(null=True, to="incident.alerttype"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("impact", models.ManyToManyField(null=True, to="incident.impact")),
                (
                    "incident_nature",
                    models.ManyToManyField(null=True, to="incident.incidentnature"),
                ),
                (
                    "primary_threat_actor",
                    models.ManyToManyField(null=True, to="incident.primarythreatactor"),
                ),
                (
                    "state",
                    models.ManyToManyField(null=True, to="accounts_profile.state"),
                ),
                (
                    "threat_level",
                    models.ManyToManyField(null=True, to="incident.threatlevel"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(blank=True)),
                ("paid", models.BooleanField(default=False)),
                ("date_from", models.DateTimeField(blank=True)),
                ("date_to", models.DateTimeField(blank=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("number_of_users", models.IntegerField(blank=True)),
                ("invoice_number", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscription.subscription",
                    ),
                ),
            ],
        ),
    ]
