# Generated by Django 4.1.3 on 2023-02-24 11:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import subscription.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("price", models.FloatField(default=0)),
                ("max_no_of_users", models.IntegerField(default=0)),
                (
                    "duration",
                    models.IntegerField(
                        default=1, help_text="Duration of the package in months"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 24, 11, 22, 6, 593716, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        default=subscription.models.Package.get_default_pk,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
