# Generated by Django 4.1.3 on 2023-03-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0002_alter_incident_affected_groups"),
        ("accounts_profile", "0001_initial"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="affected_groups",
            field=models.ManyToManyField(to="incident.affectedgroup"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="alert_type",
            field=models.ManyToManyField(to="incident.alerttype"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="impact",
            field=models.ManyToManyField(to="incident.impact"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="incident_nature",
            field=models.ManyToManyField(to="incident.incidentnature"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="primary_threat_actor",
            field=models.ManyToManyField(to="incident.primarythreatactor"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="state",
            field=models.ManyToManyField(to="accounts_profile.state"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="threat_level",
            field=models.ManyToManyField(to="incident.threatlevel"),
        ),
    ]
