# Generated by Django 4.1.3 on 2023-02-24 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 24, 11, 34, 22, 219362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
