# Generated by Django 4.1.3 on 2023-02-27 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0008_subscription_extra_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 27, 20, 0, 32, 177450)
            ),
        ),
    ]
