# Generated by Django 4.1.3 on 2023-02-27 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0009_alter_subscription_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 27, 20, 54, 17, 784434)
            ),
        ),
    ]
