# Generated by Django 4.1.3 on 2023-03-07 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0013_alter_subscription_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 7, 18, 27, 19, 149981)
            ),
        ),
    ]
