# Generated by Django 4.1.3 on 2023-03-09 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0014_alter_subscription_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 9, 5, 20, 1, 415998)
            ),
        ),
    ]
