# Generated by Django 4.1.3 on 2023-03-10 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0008_affectedgroup_alter_incident_advisory_and_more"),
        ("accounts_profile", "0002_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscription", "0015_alter_subscription_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="extra_user",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="user",
            new_name="customer",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="active",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="package",
        ),
        migrations.AddField(
            model_name="subscription",
            name="affected_groups",
            field=models.ManyToManyField(null=True, to="incident.affectedgroup"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="alert_type",
            field=models.ManyToManyField(null=True, to="incident.alerttype"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="duration",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subscription",
            name="expiry_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="impact",
            field=models.ManyToManyField(null=True, to="incident.impact"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="incident_nature",
            field=models.ManyToManyField(null=True, to="incident.incidentnature"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="number_of_users",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_status",
            field=models.CharField(
                choices=[("", ""), ("INVOICE", "INVOICE"), ("PAID", "PAID")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="primary_threat_actor",
            field=models.ManyToManyField(null=True, to="incident.primarythreatactor"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="state",
            field=models.ManyToManyField(null=True, to="accounts_profile.state"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("EXPIRED", "EXPIRED")],
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="threat_level",
            field=models.ManyToManyField(null=True, to="incident.threatlevel"),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(blank=True)),
                ("paid", models.BooleanField(default=False)),
                ("date_from", models.DateTimeField(blank=True)),
                ("date_to", models.DateTimeField(blank=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("number_of_users", models.IntegerField(blank=True)),
                ("invoice_number", models.CharField(blank=True, max_length=999999999)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscription.subscription",
                    ),
                ),
            ],
        ),
    ]
