# Generated by Django 4.1.3 on 2023-03-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0016_rename_extra_user_subscription_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=999999),
        ),
    ]
