# Generated by Django 4.1.3 on 2023-03-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0017_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_number",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_numb",
            field=models.CharField(blank=True, max_length=999999),
        ),
    ]
