# Generated by Django 4.1.3 on 2023-03-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0018_remove_invoice_invoice_number_invoice_invoice_numb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="invoice_numb",
            new_name="invoice_number",
        ),
    ]
