# Generated by Django 4.1.3 on 2023-03-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[("email", "EMAIL"), ("google", "GOOGLE"), ("added", "ADDED")],
                default="email",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("client", "CLIENT"),
                    ("company", "COMPANY"),
                    ("admin", "ADMIN"),
                ],
                default="client",
                max_length=255,
            ),
        ),
    ]
