# Generated by Django 4.1.3 on 2023-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="verification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
