# Generated by Django 4.1.3 on 2023-03-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("get", "GET"),
                            ("post", "POST"),
                            ("put", "PUT"),
                            ("delete", "DELETE"),
                        ],
                        default="get",
                        max_length=100,
                    ),
                ),
                ("module_name", models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("permissions", models.ManyToManyField(to="role.rolepermission")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
