# Generated by Django 4.1.3 on 2023-02-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("get", "GET"),
                            ("post", "POST"),
                            ("put", "PUT"),
                            ("delete", "DELETE"),
                        ],
                        default="get",
                        max_length=100,
                    ),
                ),
                ("module_name", models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name="role",
            name="permissions",
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(to="role.rolepermission"),
        ),
    ]
