# Generated by Django 4.1.3 on 2023-02-27 20:00

from django.db import migrations, models
import role.models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0002_rolepermission_remove_role_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                default=role.models.RolePermission.get_default_pk,
                to="role.rolepermission",
            ),
        ),
    ]
