# Generated by Django 4.1.3 on 2023-02-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0002_rolepermission_remove_role_permissions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="owner",
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
