# Generated by Django 4.1.3 on 2023-02-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0003_alter_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
