# Generated by Django 4.1.3 on 2023-02-27 19:52

from django.db import migrations, models
import django.db.models.deletion
import role.models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0002_rolepermission_remove_role_permissions_and_more"),
        ("accounts_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                default=role.models.Role.get_default_pk,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="role.role",
            ),
        ),
    ]
