# Generated by Django 4.1.3 on 2023-02-02 08:39

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="owner",
            field=models.ForeignKey(
                default=accounts.models.User.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
