# Generated by Django 4.1.3 on 2023-03-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="affected_groups",
            field=models.ManyToManyField(to="incident.affectedgroup"),
        ),
    ]
