# Generated by Django 4.1.3 on 2023-02-24 15:19

from django.db import migrations, models
import django.db.models.deletion
import incident.models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="evidence",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.ForeignKey(
                default=incident.models.IncidentType.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="incident.incidenttype",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="past_occurrences",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="perpetrators",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="prior_warnings",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="special_events",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
