# Generated by Django 4.1.3 on 2023-02-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0002_alter_incident_date_alter_incident_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
