# Generated by Django 4.1.3 on 2023-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0002_remove_incident_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticketassignee",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
