# Generated by Django 4.1.3 on 2023-03-09 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0006_incident_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advisory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("definition", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AlertType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("definition", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Impact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("definition", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrimaryThreatActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("definition", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThreatLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("color_code", models.CharField(max_length=20)),
                ("definition", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="incident",
            name="incident_type",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="name",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="perpetrators",
        ),
        migrations.AlterField(
            model_name="incident",
            name="past_occurrences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="advisory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incident.advisory",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="alert_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incident.alerttype",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="impact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incident.impact",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="primary_threat_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incident.primarythreatactor",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="threat_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incident.threatlevel",
            ),
        ),
    ]
