# Generated by Django 4.1.3 on 2023-02-15 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("receiver", models.CharField(max_length=20)),
                ("message", models.TextField(default="")),
                ("sent", models.BooleanField(default=False)),
                (
                    "response_message",
                    models.CharField(blank=True, max_length=525, null=True),
                ),
                ("status_code", models.CharField(max_length=225)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("receiver", models.CharField(max_length=20)),
                ("message", models.TextField(default="")),
                ("sent", models.BooleanField(default=False)),
                ("response_message", models.CharField(max_length=525)),
                ("message_id", models.CharField(max_length=225)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
