# Generated by Django 4.1.3 on 2023-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_emails_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emails",
            options={"verbose_name_plural": "Emails"},
        ),
        migrations.AlterModelOptions(
            name="messages",
            options={"verbose_name_plural": "Messages"},
        ),
        migrations.AddField(
            model_name="emails",
            name="subject",
            field=models.CharField(default="", max_length=225),
        ),
        migrations.AlterField(
            model_name="emails",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="messages",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
